# Generated by Django 5.0.3 on 2024-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['-title']},
        ),
        migrations.AlterField(
            model_name='flower',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
