# Generated by Django 5.0.3 on 2024-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_flower_options_alter_flower_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description_ar',
            field=models.TextField(default='تجربة بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='title_ar',
            field=models.CharField(default='تايتل بالعربي', max_length=100),
            preserve_default=False,
        ),
    ]
