# Generated by Django 5.0.3 on 2024-04-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_flower_description_ar_flower_title_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='user_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
