# Generated by Django 5.0.3 on 2024-04-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_flower_user_name_flower_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['-title'], 'permissions': [('test_flower', 'Test Flower')]},
        ),
    ]
